export const shoppingList = [
  {
    id: 1,
    category: 'Fresh Produce',
    name: 'Tomatoes',
    quantity: 6,
    unit: 'pcs',
  },
  {
    id: 2,
    category: 'Fresh Produce',
    name: 'Lettuce',
    quantity: 2,
    unit: 'heads',
  },
  {
    id: 3,
    category: 'Dairy',
    name: 'Milk',
    quantity: 2,
    unit: 'liters',
  },
  {
    id: 4,
    category: 'Dairy',
    name: 'Cheese',
    quantity: 1,
    unit: 'pack',
  },
  {
    id: 5,
    category: 'Bakery',
    name: 'Bread',
    quantity: 1,
    unit: 'loaf',
  },
  {
    id: 6,
    category: 'Meat & Protein',
    name: 'Chicken Breast',
    quantity: 1,
    unit: 'kg',
  },
  {
    id: 7,
    category: 'Pantry',
    name: 'Rice',
    quantity: 2,
    unit: 'kg',
  },
  {
    id: 8,
    category: 'Pantry',
    name: 'Pasta',
    quantity: 3,
    unit: 'packs',
  },
  {
    id: 9,
    category: 'Beverages',
    name: 'Green Tea',
    quantity: 1,
    unit: 'box',
  },
  {
    id: 10,
    category: 'Cleaning',
    name: 'Dish Soap',
    quantity: 1,
    unit: 'bottle',
  },
];

export const tableHeader = [
  { key: 'id', label: 'ID' },
  { key: 'category', label: 'Category' },
  { key: 'name', label: 'Item Name' },
  { key: 'quantity', label: 'Quantity' },
  { key: 'actions', label: 'Actions' },
];
